### ISSUE TITLE
Double-click text presentation bug

### ISSUE THREAD

**Issue by baranan** [ProjectImplicit/PIquest#1]
In Chrome, using the code pasted below, double-clicking a button and then moving the mouse away from the button hides the button's text:
![double](https://cloud.githubusercontent.com/assets/4257111/21565608/e80f726e-cea2-11e6-9711-5988b6d59652.gif)

```
define(['questAPI'], function(Quest){
	var API = new Quest();
	API.addSequence(
	[
	    {
            progressBar: '<%= pagesMeta.number %> out of 10',
            questions : {
        		type: 'selectOne',
        		style:'multiButtons',
        		errorMsg: {
        			required: "Please select an answer, or click 'decline to answer'"
        		},
        		name:'item1',
		        stem : 'On the whole, I am satisfied with myself.',
        		answers : ['Strongly Disagree', 'Disagree', 'Agree', 'Strongly Agree']
            }
    	}
	]);
	return API.script;
});
```

**Comment by eladzlot** [comment]
Please note that you created this issue on the wrong repository.
Any issues regarding minno-quest should be added [here](
https://github.com/minnojs/minno-quest/issues)

**Comment by eladzlot** [comment]
Reopened (and closed) on https://github.com/minnojs/minno-quest/issues/147
