### ISSUE TITLE
requiredText property in question types

### ISSUE THREAD

**Issue by baranan** [ProjectImplicit/PIquest#109]
When the user sets required=true the current "error" test that appears when a question is not answered is "This field is required". For some questions (at least for slider) this message is not perfect (slider is not exactly a field). So let users change this default message with a requiredText property (default "Please answer this question").

**Comment by eladzlot** [comment]
You can already do that using the errorMsg object
```js
{
  type: 'slider',
  require: true,
  errorMsg: {
    required: 'my custom message'
  }
}
```
If you'd like a different default message, it is very simple to change...
