### ISSUE TITLE
pageData pagesData? Where is the documentation for this?

### ISSUE THREAD

**Issue by baranan** [ProjectImplicit/PIquest#143]
I wanted to make sure how I am supposed to find page data. I could find PageData or PagesData in the documentation site. So I searched for questionsData, but couldn't find any page that provides this information. Only code that includes questionsData and nothing about how to access the page's data object.

**Comment by eladzlot** [comment]
The documentation is right here:
http://projectimplicit.github.io/PIquest/0.0/basics/
sequencer.html#local-variables
http://projectimplicit.github.io/PIquest/0.1/sequencer/variables.html#local-
variables-local-&-meta

using google for site search is evidently not good enough for us.
We might want to consider alternatives
