### ISSUE TITLE
Old questionnaire doesn't work anymore

### ISSUE THREAD

**Issue by baranan** [ProjectImplicit/PIquest#145]
I need to provide reviewers access to experience a study that was conducted on July-Sep 2015, but one of the questionnaires does not work as it used to. 
You can see the study at 
https://app-prod-03.implicit.harvard.edu/implicit/showfiles.jsp?user=yba&study=cmpform2
The questionnaire is at
https://app-prod-03.implicit.harvard.edu/implicit/user/yba/cmpform2/ratemen.js

The problem: it seems that the repeat mixer doesn't work. I see only one question before the sequence ends. 
Note that the file is complicated because I selected one of six different questionnaire formats for testing.

**Comment by eladzlot** [comment]
This has to do with a bug fix from a while ago.
"choose" should pick only one element from its subsequence, you want it to
pick a whole mixer, so you should add wrapper:true to the mixers.

**Comment by baranan** [comment]
Yes, it is fixed now.
