### ISSUE TITLE
maxLength in text

### ISSUE THREAD

**Issue by baranan** [ProjectImplicit/PIquest#71]
1 maxLength should simply prevent adding more characters (rather than showing a "too long" warning).

2 It will be better if the length of the text-box would be according to the maxLength. It is odd when I limit the length of the response to 30 characters, but the text-box is much longer.

**Comment by eladzlot** [comment]
@baranan 
There is a usability issue here. If users attempt to insert a response and nothing happens, they'll feel that something is broken.
Also, it is not straightforward to shorten the input in accordance with the maxLength (The same lenght can have multiple text widths and it gets out of hand quite quickly...). If you want a narrower input, simply use the inline property #72.

**Comment by baranan** [comment]
1. ok. So prevent adding and show also a warning, but allow researchers to ask for removing that warning (no-warning).

2. Do you mean the same-line feature?  (the link from #72 is not clear. It might have been better if the message that closes the issue explicitly documented what new feature was added). It doesn't sound like a perfect solution because it will probably be fine for some lengths and too much/too little for other lengths. Perhaps add another property to set the size/length of the text-area.

**Comment by eladzlot** [comment]
1. allright
2. Yes, I mean the same line feature. Setting the width explicitly is begging for trouble. I highly recommend to avoid it.

**Comment by baranan** [comment]
2. And if we don't mess with the width, can we at least set the number of lines?

**Comment by eladzlot** [comment]
@baranan: This is one option, but the idea is that it depends on the question how long the answer is expected to be. Sometimes we want only a word, sometimes 10, sometimes three lines and sometimes a whole essay. So the whole idea is that it would help researchers if they can control the size of the input box.

I see, you want a textarea input. Moving that discussion to #95
