### ISSUE TITLE
feat(piqPage): Countdown clock

### ISSUE THREAD

**Issue by baranan** [ProjectImplicit/PIquest#86]
When using timeout for a page, users should have the option to display a timer.

**Comment by eladzlot** [comment]
What happens when a page times out?
1. We proceed to the next page
2. We mark the log with log.timeout = true (how does the PI backend deal with this situation).

**Comment by baranan** [comment]
You can also allow showing a custom message, and disabling all buttons other than "proceed".

**Comment by eladzlot** [comment]
This has been implemented on 89fdb6b.
Lets see what people need before developing it further.
