### ISSUE TITLE
feat(questDirectives): a table type series of questions

### ISSUE THREAD

**Issue by eladzlot** [ProjectImplicit/PIquest#97]
This is useful for series of many likert type questions.

We probably need a parent questions that creates several sub questions with the questController.
The sub questions are very similar to the selectOne questions.

**Comment by eladzlot** [comment]
How about something like this:
```js
var gridQuest = {
	type: 'grid',
	stem: 'How tasty are:',
	columns:['Very', 'Medium', 'Not'],
    advancedColumns: [{text:'High', value:7}, {text:'Low', value:1}],
	rows: [
		{name:'a01', stem:'Bannanas'},
		{name:'a02', stem:'Apples', required: true},
		{name:'a03', stem:'Grapes'}
	]
};
```

It should create a table with check-boxes.
Allow randomization of rows (using the mixer, same as selectOne).
Maybe we can keep track of the sum of results? If so it is critical to have an explicit flip property.
In the future we may want different types of columns (n/a, other=text).

**Comment by baranan** [comment]
@eladzlot I think it makes sense to implement this feature with a question type that has sub questions as properties. Researchers will probably easily understand that there is a type of question that includes a series of sub-questions. So, I recommend adding it with AddQuestionsSet. 

Regarding the actual feature:
- I think that it will look best if the check boxes are implemented as a selection of a rectangle in the row (perhaps with a V sign, or coloring the selected cell in black [can also add properties to change colors]).
- Another possible way to indicate selection is to print the response label of the selected cell in a large bold font inside the selected cell.
- Allow researchers show the response labels in each row (will appear by default only at the top row).

- Based on this question type, you can also create two other useful types: 
	- Matching (don't allow selecting the same response option in two different rows of the same table): for instance, if the response options are words in French and the questions are words in English, and the participants should match each word to the correct translation.
	- Ranking (based on a Matching question, but participants match rank to each item, and an additional button re-order the items by rank).

- Different types of columns is a good idea.
